### ISSUE TITLE
Unable to re size window

### ISSUE THREAD

**Issue by cloudleon** [hickabilly/PoGo.PokeMobBot.GUI#3]
Unable to re size window, some setting cant see, here the screenshot http://imgur.com/a/M4VWC

**Comment by hickabilly** [comment]
Thanks.  I built it for a minimum of 600x800.  I will work on letting it resize this evening after work.

**Comment by hickabilly** [comment]
Modified to allow horizontal and vertical stretching with a minimum size. Adjusted internal objects to move appropriately when window is stretched.

**Comment by cloudleon** [comment]
Done viewing, nice update
