### ISSUE TITLE
Unable to save setting

### ISSUE THREAD

**Issue by cloudleon** [hickabilly/PoGo.PokeMobBot.GUI#5]
I already make lot of change at all tab, but when press "Apply" button (I assume this button for save current setting) and restart the program, all my setting note saved. It revert to original setting.

**Comment by hickabilly** [comment]
There isn't any connection to the main PokeMobBot yet.  This is purely a UI design.  The only thing that is implemented is the controls to show what will be enabled or disabled when various options are chosen.  This is just a prototype GUI that I am offering to integrate into the main project if they like it.

**Comment by cloudleon** [comment]
I see, are you already told them about this project?

**Comment by hickabilly** [comment]
Yes, I have offered it up to the lead on the project on Sunday evening.  They have said that they will consider it.  If they decide not to go with it, I will take out the Status and Pokémon tabs and possibly turn it into a configurator for the project that will be independent of the project.  Not sure yet how it will go.
